version: '3.7'

services:
    redis:
        image: "redis:alpine"
    monitoring:
        image: "palacios3mw/monitor:latest"  
        ports:
            - "5000:5000"
    web:
        build: .
        command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
        environment:
            - ENVIRONMENT=production
            - SECRET_KEY=43%0+@56zgw+-8s-xvm6#u0v)#@wlun5oir0h^)+tz_attmi!z
            - DEBUG=0
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on:
            - db
            - monitoring
    celery:
        environment:
            - C_FORCE_ROOT=true
            - SECRET_KEY=43%0+@56zgw+-8s-xvm6#u0v)#@wlun5oir0h^)+tz_attmi!z
        build: .    
        command: bash -c "python manage.py celery worker"
        volumes:
            - .:/code
        depends_on:
            - redis
            - db
    celery-beat:
        build: .
        command: bash -c "python manage.py celery beat"
        environment:
            - SECRET_KEY=43%0+@56zgw+-8s-xvm6#u0v)#@wlun5oir0h^)+tz_attmi!z
        volumes:
            - .:/code
        depends_on:
            - redis
            - db
    db:
        image: postgres:11
        volumes:
          - postgres_data:/var/lib/postgresql/data/
volumes:
    postgres_data:
      